# Generated by Django 3.2.5 on 2021-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmId',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
