# Generated by Django 3.2.5 on 2021-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210705_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(blank=True, max_length=100, null=True)),
                ('staffId', models.IntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('professionText', models.CharField(blank=True, max_length=55, null=True)),
                ('professionKey', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
