# Generated by Django 3.2.5 on 2021-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210714_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='teasers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='trailers',
            field=models.JSONField(default=list),
        ),
    ]
