# Generated by Django 3.2.5 on 2021-10-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('slug', models.SlugField(blank=True, max_length=510, null=True, unique=True)),
                ('year', models.CharField(max_length=32)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(max_length=255)),
                ('filmId', models.IntegerField(blank=True, null=True, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=510, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filmLength', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('ratingAgeLimits', models.CharField(blank=True, max_length=64, null=True)),
                ('premiereRu', models.CharField(blank=True, max_length=64, null=True)),
                ('premiereWorld', models.CharField(blank=True, max_length=64, null=True)),
                ('premiereDigital', models.CharField(blank=True, max_length=64, null=True)),
                ('premiereWorldCountry', models.CharField(blank=True, max_length=64, null=True)),
                ('facts', models.JSONField(default=list)),
                ('budget', models.CharField(blank=True, max_length=64, null=True)),
                ('grossRu', models.BigIntegerField(blank=True, null=True)),
                ('grossUsa', models.BigIntegerField(blank=True, null=True)),
                ('grossWorld', models.BigIntegerField(blank=True, null=True)),
                ('trailers', models.JSONField(default=list)),
                ('teasers', models.JSONField(default=list)),
                ('countries', models.ManyToManyField(to='kinopoiskclone.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRu', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('staffId', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=511, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('professionText', models.CharField(blank=True, max_length=64, null=True)),
                ('professionKey', models.CharField(blank=True, max_length=64, null=True)),
                ('birthday', models.CharField(blank=True, max_length=64, null=True)),
                ('death', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('growth', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_films', models.ManyToManyField(to='kinopoiskclone.Film')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='kinopoiskclone.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='staff',
            field=models.ManyToManyField(to='kinopoiskclone.Staff'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['type'], name='kinopoiskcl_type_05caf0_idx'),
        ),
    ]
