# Generated by Django 3.2.5 on 2021-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('rating', models.CharField(max_length=5)),
                ('image', models.CharField(max_length=255)),
                ('filmId', models.IntegerField(null=True, unique=True)),
            ],
        ),
    ]
