# Generated by Django 3.2.5 on 2021-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['type', 'id', 'name', 'year', 'image'], name='kinopoiskcl_type_42e33d_idx'),
        ),
    ]
