# Generated by Django 3.2.5 on 2021-10-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0002_film_kinopoiskcl_type_42e33d_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='film',
            name='kinopoiskcl_type_42e33d_idx',
        ),
    ]
