# Generated by Django 3.2.5 on 2021-10-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0003_remove_film_kinopoiskcl_type_42e33d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['id', 'name', 'year', 'image'], name='kinopoiskcl_id_cbf64e_idx'),
        ),
    ]
