# Generated by Django 3.2.5 on 2021-12-06 21:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations
from django.contrib.postgres.search import SearchVector

from kinopoiskclone.models import Film


def index_entries(apps, schema_editor):
    Film.objects.update(vector_name=SearchVector('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0005_auto_20211205_1202'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='film',
            name='vector_name',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RunPython(index_entries),
        migrations.AddIndex(
            model_name='film',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_name'], name='kinopoiskcl_vector__46fc9a_gin'),
        ),
    ]
