# Generated by Django 3.2.5 on 2021-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0006_film_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='facts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='grossRu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='grossUsa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='grossWorld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(to='kinopoiskclone.Country'),
        ),
    ]
