# Generated by Django 3.2.5 on 2021-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0009_auto_20210723_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='filmId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
