# Generated by Django 3.2.5 on 2021-08-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0012_auto_20210728_1717'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['rating', 'type'], name='backend_fil_rating_24256c_idx'),
        ),
    ]
