# Generated by Django 3.2.5 on 2021-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0013_film_backend_fil_rating_24256c_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='film',
            name='backend_fil_rating_24256c_idx',
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['rating', 'type'], name='kinopoiskcl_rating_f28b22_idx'),
        ),
    ]
