# Generated by Django 3.2.5 on 2021-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0015_auto_20210918_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birthday',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='death',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='professionKey',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='professionText',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
