# Generated by Django 3.2.5 on 2021-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0016_auto_20210918_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
