# Generated by Django 3.2.5 on 2021-09-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0017_alter_staff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='grossRu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='grossUsa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='grossWorld',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
