# Generated by Django 3.2.5 on 2021-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0018_auto_20210918_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmLength',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='premiereDigital',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='premiereRu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='premiereWorld',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='premiereWorldCountry',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='ratingAgeLimits',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=32),
        ),
    ]
