# Generated by Django 3.2.5 on 2021-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0019_auto_20210918_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=510),
        ),
        migrations.AlterField(
            model_name='film',
            name='slogan',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=510, null=True, unique=True),
        ),
    ]
