# Generated by Django 3.2.5 on 2021-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='savedFilms',
            field=models.ManyToManyField(to='kinopoiskclone.Film'),
        ),
    ]
