# Generated by Django 3.2.5 on 2021-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoiskclone', '0022_userprofile_savedfilms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='savedFilms',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_films',
            field=models.ManyToManyField(to='kinopoiskclone.Film'),
        ),
    ]
